name: Bug Report / Support Request
description: Report issues or ask for help with the Modbus integration.
title: "[Bug/Support] - [Short Description]"
labels: ["bug", "support"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please complete **all fields**. Without full information (especially log files), we cannot investigate your issue.

        ⚠️ **Important Firmware Note**  
        Please ensure that you always have the latest version installed:  
        https://github.com/stanus74/home-assistant-saj-h2-modbus/releases  

        **Do not post an error message if you have set the polling interval to less than 60 seconds.  
        Modbus protocol is not Gigabit LAN :-)**

  - type: input
    id: inverter_model
    attributes:
      label: Inverter model
      description: e.g., "SAJ H1-6-S2"
      placeholder: "SAJ H1-6-S2"
    validations:
      required: true

  - type: input
    id: integration_version
    attributes:
      label: Integration version
      description: Which release of the Modbus integration are you using?
      placeholder: "e.g., v1.2.3"
    validations:
      required: true

  - type: dropdown
    id: modbus_converter
    attributes:
      label: Which Modbus TCP converter are you using?
      options:
        - AIO3
        - AIO2
        - USR-TCP232
        - Waveshare
        - Other (please specify below)
    validations:
      required: true

  - type: textarea
    id: converter_details
    attributes:
      label: Additional converter details (if "Other" selected)
      description: Manufacturer, model, etc.
    validations:
      required: false

  - type: textarea
    id: issue_description
    attributes:
      label: Describe the issue
      description: When does it happen? Do all sensors show "unknown"? Any pattern?
    validations:
      required: true

  - type: input
    id: ha_version
    attributes:
      label: Home Assistant version
      placeholder: "e.g., 2025.5.0"
    validations:
      required: true

  - type: dropdown
    id: ha_install
    attributes:
      label: Installation type
      options:
        - Home Assistant OS
        - Home Assistant Container
        - Home Assistant Supervised
        - Core (venv/manual install)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: Copy relevant lines or attach the full log file
    validations:
      required: true

  - type: checkboxes
    id: pre_checks
    attributes:
      label: Pre-checks
      options:
        - label: I confirmed the inverter is reachable via Modbus TCP
          required: true
        - label: I searched for existing issues
          required: true
        - label: I removed the integration and performed a clean reinstallation.
          required: true

  - type: markdown
    attributes:
      value: |
        ✅ Thanks for helping improve this integration!

        ---
        ⚠️ **Please read carefully before submitting a question:**

        This is a **community-driven hobby project**. SAJ offers **no official support**, and everything here is based on reverse engineering in spare time.

        Before submitting, please:

        - Make sure your question actually relates to this integration and not to general Home Assistant behavior (e.g. Energy dashboard display, template sensors, etc.)
        - Double-check the [README](https://github.com/stanus74/home-assistant-saj-h2-modbus) and existing issues.
        - Use the [Home Assistant Forum](https://community.home-assistant.io) for HA-specific questions.

        Thanks for your understanding!
